name: Readme Weather Update

# Trigger the workflow on a schedule and allow manual triggers
on:
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours
  workflow_dispatch:

jobs:
  update-readme-weather:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner environment

    steps:
      # Step 1: Checkout the weather script repository
      - name: Checkout Weather Script Repository
        uses: actions/checkout@v4  
        with:
          repository: tashfiqul-islam/git-profile-weather-view 
          path: git-profile-weather-view  

      # Step 2: Checkout the personal repository
      - name: Checkout Personal Repository
        uses: actions/checkout@v4
        with:
          repository: tashfiqul-islam/tashfiqul-islam
          path: tashfiqul-islam 
          token: ${{ secrets.PAT }}  # Personal Access Token for authentication

      # Step 3: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  

      # Step 4: Install dependencies for the weather script
      - name: Install Dependencies
        run: npm install
        working-directory: ./git-profile-weather-view 

      # Step 5: Execute the weather script to fetch data
      - name: Run Weather Script
        run: |
          WEATHER_DATA=$(node src/index.js)  # Fetch weather data
          echo "WEATHER_DATA=$WEATHER_DATA" >> $GITHUB_ENV  # Export weather data as an environment variable
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}  # API key for OpenWeatherMap
        working-directory: ./git-profile-weather-view

      # Step 6: Update the README with the new weather data
      - name: Update README
        run: node src/updateReadme.js "${{ env.WEATHER_DATA }}"  # Pass weather data to the script
        working-directory: ./git-profile-weather-view

      # Step 7: Import GPG key for commit signing
      - name: Import GPG Key
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --homedir ~/.gnupg --batch --import --no-tty --pinentry-mode loopback
        shell: bash
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}  # Use the passphrase stored in secrets

      # Step 8: Configure Git with user details and GPG settings
      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"  # Set user email for commits
          git config --global user.name "${{ secrets.GH_USERNAME }}"  # Set user name for commits
          git config --global user.signingkey "${{ secrets.GPG_SIGN_KEY }}"  # Set GPG signing key
          git config --global gpg.program $(which gpg)  # Use the installed GPG program
          git config --global commit.gpgsign true  # Enable GPG signing for commits
        working-directory: ./tashfiqul-islam

      # Step 9: Commit and push changes if the README has been updated
      - name: Commit and push if changed
        run: |
          cd tashfiqul-islam
          git diff
          if [ -n "$(git diff --name-only)" ]; then
            git commit -S -am "chore(profile-weather-view): Hourly Weather Update"
            git push origin master
          else
            echo "No changes to commit"
          fi
