name: Readme Weather Update

# Trigger the workflow on a schedule and allow manual triggers
on:
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours
  workflow_dispatch:

jobs:
  update-readme-weather:
    runs-on: ubuntu-latest 

    steps:
      # Step 1: Checkout the weather script repository
      - name: Checkout Weather Script Repository
        uses: actions/checkout@v4
        with:
          repository: tashfiqul-islam/git-profile-weather-view
          path: git-profile-weather-view

      # Step 2: Checkout the personal repository
      - name: Checkout Personal Repository
        uses: actions/checkout@v4
        with:
          path: tashfiqul-islam
          token: ${{ secrets.PAT }}  # Personal Access Token stored in secrets

      # Step 3: Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x' 

      # Step 4: Install dependencies for the weather script
      - name: Install Dependencies
        run: npm ci  # Clean install to ensure a fresh dependency setup
        working-directory: ./git-profile-weather-view

      # Step 5: Execute the weather script to fetch data
      - name: Run Weather Script
        run: |
          WEATHER_DATA=$(node src/index.js)
          echo "WEATHER_DATA=$WEATHER_DATA" >> $GITHUB_ENV
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}  # API key stored in secrets
        working-directory: ./git-profile-weather-view

      # Step 6: Update the README with the new weather data
      - name: Update README
        run: node src/updateReadme.js "${{ env.WEATHER_DATA }}"
        working-directory: ./git-profile-weather-view

      # Step 7: Import GPG key for commit signing
      - name: Import GPG Key
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --batch --import --pinentry-mode loopback
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}  # Passphrase stored in secrets

      # Step 8: Configure Git with user details and GPG settings
      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git config --global user.signingkey "${{ secrets.GPG_SIGN_KEY }}"
          git config --global gpg.program $(which gpg)
          git config --global commit.gpgsign true

      # Step 9: Commit and push changes if the README has been updated
      - name: Commit and Push Changes
        run: |
          cd tashfiqul-islam
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "chore: update weather data" --no-verify
            git push origin master
          else
            echo "No changes to commit"
          fi
