name: Readme Weather Update

# 🚀 Trigger Mechanisms for GitHub Actions
on:
  schedule:
    - cron: '0 */8 * * *' # Runs automatically every 8 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme-weather:
    runs-on: ubuntu-latest

    # 🏎️ Strategy matrix to parallelize tasks
    strategy:
      matrix:
        task: [checkout-repos, setup-bun, install-deps, fetch-weather, update-readme, commit-push]

    steps:
      # ✅ Step 1: Checkout the weather script repository
      - name: Checkout Weather Script Repository
        if: matrix.task == 'checkout-repos'
        uses: actions/checkout@v4
        with:
          repository: tashfiqul-islam/git-profile-weather-view
          path: git-profile-weather-view

      # ✅ Step 2: Authenticate GitHub with OIDC
      - name: Authenticate GitHub with OIDC
        if: matrix.task == 'checkout-repos'
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Step 3: Checkout Personal Repository (Using OIDC)
      - name: Checkout Personal Repository
        if: matrix.task == 'checkout-repos'
        uses: actions/checkout@v4
        with:
          repository: tashfiqul-islam/tashfiqul-islam
          path: tashfiqul-islam
          token: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Step 4: Setup Bun
      - name: Setup Bun
        if: matrix.task == 'setup-bun'
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # ✅ Step 5: Cache Bun Dependencies for Faster Installs
      - name: Cache Bun Dependencies
        if: matrix.task == 'setup-bun'
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # ✅ Step 6: Install Dependencies using Bun
      - name: Install Dependencies
        if: matrix.task == 'install-deps'
        run: bun install
        working-directory: ./git-profile-weather-view

      # ✅ Step 7: Fetch Weather Data and Save to File
      - name: Fetch Weather Data
        if: matrix.task == 'fetch-weather'
        run: |
          bun run src/index.ts > weather.json
          echo "WEATHER_DATA=$(cat weather.json)" >> $GITHUB_ENV
        working-directory: ./git-profile-weather-view

      # ✅ Step 8: Upload Weather Data as Artifact (Persists Across Jobs)
      - name: Upload Weather Data
        if: matrix.task == 'fetch-weather'
        uses: actions/upload-artifact@v4
        with:
          name: weather-data
          path: ./git-profile-weather-view/weather.json

      # ✅ Step 9: Download Weather Data Before Updating README
      - name: Download Weather Data
        if: matrix.task == 'update-readme'
        uses: actions/download-artifact@v4
        with:
          name: weather-data

      # ✅ Step 10: Update the README File with New Weather Data
      - name: Update README
        if: matrix.task == 'update-readme'
        run: bun run src/updateReadme.ts "$(cat weather.json)"
        working-directory: ./git-profile-weather-view

      # ✅ Step 11: Configure Git for Commit Signing (Using GitHub's Built-in GPG)
      - name: Configure Git for Signing
        if: matrix.task == 'commit-push'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global commit.gpgsign true
          git config --global gpg.format ssh
          git config --global user.signingkey ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./tashfiqul-islam

      # ✅ Step 12: Commit and Push Changes if README was Updated
      - name: Commit & Push Changes
        if: matrix.task == 'commit-push'
        run: |
          export GPG_TTY=$(tty)
          cd tashfiqul-islam
          
          # Check if README.md has changed before committing
          git add README.md
          if git diff --cached --quiet; then
            echo "✅ No changes to commit."
          else
            git commit -S -m "chore(profile-weather-view): Hourly Weather Update"
            git push origin master
          fi
