name: Update README Weather

# Trigger the workflow every hour and also allow manual triggers
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest  # Specification of the runner environment

    steps:
      # Checkout the repository containing the weather view script
      - name: Checkout git-profile-weather-view repository
        uses: actions/checkout@v4
        with:
          repository: tashfiqul-islam/git-profile-weather-view
          path: git-profile-weather-view

      # Checkout your personal repository where the README will be updated
      - name: Checkout tashfiqul-islam/tashfiqul-islam repository
        uses: actions/checkout@v4
        with:
          repository: tashfiqul-islam/tashfiqul-islam
          path: tashfiqul-islam
          token: ${{ secrets.PAT }}

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Install dependencies for the weather script
      - name: Install dependencies
        run: npm install
        working-directory: ./git-profile-weather-view

      # Execute the weather script and set the output as an environment variable
      - name: Run Weather Script
        run: |
          WEATHER_DATA=$(node src/index.js)
          echo "WEATHER_DATA=$WEATHER_DATA" >> $GITHUB_ENV
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        working-directory: ./git-profile-weather-view

      # Update the README with the new weather data
      - name: Update README
        run: node src/updateReadme.js "${{ env.WEATHER_DATA }}"
        working-directory: ./git-profile-weather-view

      # Import GPG key for commit signing
      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode | gpg --batch --import --no-tty --pinentry-mode loopback
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        shell: bash

      # Configure Git with your user details and GPG signing
      - name: Configure Git
        run: |
          git config --global user.email "${{ secrets.GH_EMAIL }}"
          git config --global user.name "${{ secrets.GH_USERNAME }}"
          git config --global user.signingkey "${{ secrets.GPG_KEY_ID }}"
          git config --global commit.gpgsign true
        working-directory: ./tashfiqul-islam

      # Commit and push changes if there are any changes to the README
      - name: Commit and push if changed
        run: |
          cd tashfiqul-islam
          git diff
          if [ -n "$(git diff --name-only)" ]; then
            git commit -S -am "update(profile-weather-view): Hourly Weather Update"
            git push origin master
          else
            echo "No changes to commit"
          fi
